version: '3.9'

services:
  backend:
    build: .
    container_name: api-vehicle-user
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=03-08-2004
      - DB_NAME=vehicle_user_db
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_here
      - API_TOKEN=123456789abcdef
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 03-08-2004
      MYSQL_DATABASE: vehicle_user_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./seeders/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

init.sql:
  USE vehicle_user_db;
  SHOW TABLES;