openapi: 3.0.0
info:
  title: Vehicle Management System
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Home route
      responses:
        '200':
          description: Success
